version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_portgonext
    environment:
      POSTGRES_USER: portgonext
      POSTGRES_PASSWORD: kishi1021
      POSTGRES_DB: portgonext
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
